"""create notification message table

Revision ID: 8057b0f30343
Revises: 018ee234cbf6
Create Date: 2026-09-19 01:36:45.000218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8057b0f30343'
down_revision: Union[str, Sequence[str], None] = '018ee234cbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('notifications',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('notification_uuid', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('WELCOME', 'EMAIL_VERIFIED', 'PASSWORD_CHANGED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('messages')
    # ### end Alembic commands ###
