"""create table

Revision ID: 018ee234cbf6
Revises: 
Create Date: 2026-08-26 15:48:56.041379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '018ee234cbf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_table('phonedetails',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('operator_type', sa.Enum('MTS', 'MEGAFON', 'BEELINE', name='operatortype'), nullable=False),
    sa.Column('region_type', sa.Enum('MOSCOW_CITY', 'SAINT_PETERSBURG', 'MOSCOW_OBLAST', 'KRASNODAR_KRAI', 'REPUBLIC_OF_TATARSTAN', 'OTHER', name='regiontype'), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phonedetails')
    op.drop_table('operations')
    # ### end Alembic commands ###
